#!/usr/bin/env bash

CMD=("$@")

case "$1" in
  require|r|install|i|update|remove|create-project)
    CMD+=("--ignore-platform-reqs")
    ;;
esac

docker run --rm --interactive \
    -u "$(id -u):$(id -g)" \
    -v "$PWD/src:/app" \
    -w /app \
    composer:latest \
    "${CMD[@]}"